// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MysqlConsoleApp;

#nullable disable

namespace MysqlConsoleApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230104034930_Create")]
    partial class Create
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Bpmtk.Engine.Models.ActivityInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("ActivityId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("activity_id");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("activity_type");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<bool>("IsMIRoot")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_mi_root");

                    b.Property<DateTime>("LastStateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_state_time");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<long>("ProcessInstanceId")
                        .HasColumnType("bigint")
                        .HasColumnName("proc_inst_id");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_time");

                    b.Property<int>("State")
                        .HasColumnType("int")
                        .HasColumnName("state");

                    b.Property<long?>("SubProcessInstanceId")
                        .HasColumnType("bigint")
                        .HasColumnName("sub_proc_inst_id");

                    b.Property<long?>("TokenId")
                        .IsRequired()
                        .HasColumnType("bigint")
                        .HasColumnName("token_id");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProcessInstanceId");

                    b.HasIndex("SubProcessInstanceId");

                    b.ToTable("bpm_act_inst", (string)null);
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.ActivityVariable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long?>("ActivityInstanceId")
                        .HasColumnType("bigint")
                        .HasColumnName("act_inst_id");

                    b.Property<long?>("ByteArrayId")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_array_id");

                    b.Property<double?>("DoubleValue")
                        .HasColumnType("double")
                        .HasColumnName("double_val");

                    b.Property<long?>("LongValue")
                        .HasColumnType("bigint")
                        .HasColumnName("long_val");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name");

                    b.Property<string>("Text")
                        .HasColumnType("longtext")
                        .HasColumnName("text");

                    b.Property<string>("Text2")
                        .HasColumnType("longtext")
                        .HasColumnName("text2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ActivityInstanceId");

                    b.HasIndex("ByteArrayId");

                    b.ToTable("bpm_act_data", (string)null);
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.ByteArray", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<byte[]>("Value")
                        .HasColumnType("longblob")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("bpm_byte_array", (string)null);
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("body");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<int?>("ProcessDefinitionId")
                        .HasColumnType("int")
                        .HasColumnName("proc_def_id");

                    b.Property<long?>("ProcessInstanceId")
                        .HasColumnType("bigint")
                        .HasColumnName("proc_inst_id");

                    b.Property<long?>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_id");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ProcessDefinitionId");

                    b.HasIndex("ProcessInstanceId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("bpm_comment", (string)null);
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.Deployment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("Memo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("memo");

                    b.Property<long?>("ModelId")
                        .HasColumnType("bigint")
                        .HasColumnName("model_id");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int?>("PackageId")
                        .HasColumnType("int")
                        .HasColumnName("package_id");

                    b.Property<string>("TenantId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UserId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.HasIndex("PackageId");

                    b.ToTable("bpm_deployment", (string)null);
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.EventSubscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("ActivityId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("activity_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("event_name");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("event_type");

                    b.Property<int?>("ProcessDefinitionId")
                        .HasColumnType("int")
                        .HasColumnName("proc_def_id");

                    b.Property<long?>("ProcessInstanceId")
                        .HasColumnType("bigint")
                        .HasColumnName("proc_inst_id");

                    b.Property<string>("TenantId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("tenant_id");

                    b.Property<long?>("TokenId")
                        .HasColumnType("bigint")
                        .HasColumnName("token_id");

                    b.HasKey("Id");

                    b.HasIndex("ProcessDefinitionId");

                    b.HasIndex("ProcessInstanceId");

                    b.HasIndex("TokenId");

                    b.ToTable("bpm_event_subscr", (string)null);
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.Group", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("bpm_group", (string)null);
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.HistoricModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("comment");

                    b.Property<long>("ContentId")
                        .HasColumnType("bigint")
                        .HasColumnName("content_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<int>("PackageId")
                        .HasColumnType("int")
                        .HasColumnName("package_id");

                    b.Property<string>("UserId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("PackageId");

                    b.ToTable("bpm_hi_model", (string)null);
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.HistoricPackageItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("comment");

                    b.Property<long>("ContentId")
                        .HasColumnType("bigint")
                        .HasColumnName("content_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<string>("UserId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("ItemId");

                    b.ToTable("bpm_hi_package_item", (string)null);
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.IdentityLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long?>("ActivityInstanceId")
                        .HasColumnType("bigint")
                        .HasColumnName("act_inst_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("GroupId")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("group_id");

                    b.Property<int?>("PackageId")
                        .HasColumnType("int")
                        .HasColumnName("package_id");

                    b.Property<int?>("ProcessDefinitionId")
                        .HasColumnType("int")
                        .HasColumnName("proc_def_id");

                    b.Property<long?>("ProcessInstanceId")
                        .HasColumnType("bigint")
                        .HasColumnName("proc_inst_id");

                    b.Property<long?>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_id");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ActivityInstanceId");

                    b.HasIndex("GroupId");

                    b.HasIndex("PackageId");

                    b.HasIndex("ProcessDefinitionId");

                    b.HasIndex("ProcessInstanceId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("bpm_identity_link", (string)null);
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("owner_id");

                    b.Property<long?>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    b.Property<string>("TenantId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SourceId");

                    b.ToTable("bpm_package", (string)null);
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.PackageItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<long?>("ContentId")
                        .HasColumnType("bigint")
                        .HasColumnName("content_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int>("PackageId")
                        .HasColumnType("int")
                        .HasColumnName("package_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("PackageId");

                    b.ToTable("bpm_package_item", (string)null);
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.ProcessDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<int>("DeploymentId")
                        .HasColumnType("int")
                        .HasColumnName("deployment_id");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<bool>("HasDiagram")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("has_diagram");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("key");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("State")
                        .HasColumnType("int")
                        .HasColumnName("state");

                    b.Property<string>("TenantId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("valid_to");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.Property<string>("VersionTag")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("version_tag");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentId");

                    b.HasIndex("Key", "Version")
                        .IsUnique();

                    b.ToTable("bpm_proc_def", (string)null);
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.ProcessInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long?>("CallerId")
                        .HasColumnType("bigint")
                        .HasColumnName("caller_id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("EndReason")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("end_reason");

                    b.Property<string>("Initiator")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("initiator");

                    b.Property<string>("Key")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("key");

                    b.Property<DateTime>("LastStateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_state_time");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("ProcessDefinitionId")
                        .HasColumnType("int")
                        .HasColumnName("proc_def_id");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_time");

                    b.Property<int>("State")
                        .HasColumnType("int")
                        .HasColumnName("state");

                    b.Property<long?>("SuperId")
                        .HasColumnType("bigint")
                        .HasColumnName("super_id");

                    b.Property<string>("TenantId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("tenant_id");

                    b.Property<long?>("TokenId")
                        .HasColumnType("bigint")
                        .HasColumnName("token_id");

                    b.Property<long?>("TokenId1")
                        .HasColumnType("bigint")
                        .HasColumnName("token_id1");

                    b.Property<long?>("TokenId2")
                        .HasColumnType("bigint")
                        .HasColumnName("token_id2");

                    b.HasKey("Id");

                    b.HasIndex("CallerId");

                    b.HasIndex("ProcessDefinitionId");

                    b.HasIndex("SuperId");

                    b.HasIndex("TokenId");

                    b.ToTable("bpm_proc_inst", (string)null);
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.ScheduledJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("ActivityId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("activity_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("due_date");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<string>("Handler")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("handler");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("key");

                    b.Property<string>("Message")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("message");

                    b.Property<string>("Options")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("options");

                    b.Property<int?>("ProcessDefinitionId")
                        .HasColumnType("int")
                        .HasColumnName("proc_def_id");

                    b.Property<long?>("ProcessInstanceId")
                        .HasColumnType("bigint")
                        .HasColumnName("proc_inst_id");

                    b.Property<int>("Retries")
                        .HasColumnType("int")
                        .HasColumnName("retries");

                    b.Property<string>("StackTrace")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("stack_trace");

                    b.Property<long?>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_id");

                    b.Property<string>("TenantId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("tenant_id");

                    b.Property<long?>("TokenId")
                        .HasColumnType("bigint")
                        .HasColumnName("token_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("ProcessDefinitionId");

                    b.HasIndex("ProcessInstanceId");

                    b.HasIndex("TaskId");

                    b.HasIndex("TokenId");

                    b.ToTable("bpm_scheduled_job", (string)null);
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.TaskInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("ActivityId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("activity_id");

                    b.Property<long?>("ActivityInstanceId")
                        .HasColumnType("bigint")
                        .HasColumnName("act_inst_id");

                    b.Property<string>("Assignee")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("assignee");

                    b.Property<DateTime?>("ClaimedTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("claimed_time");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<int?>("DelegationState")
                        .HasColumnType("int")
                        .HasColumnName("delegation_state");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("due_date");

                    b.Property<DateTime>("LastStateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_state_time");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Owner")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("owner");

                    b.Property<short>("Priority")
                        .HasColumnType("smallint")
                        .HasColumnName("priority");

                    b.Property<int?>("ProcessDefinitionId")
                        .HasColumnType("int")
                        .HasColumnName("proc_def_id");

                    b.Property<long?>("ProcessInstanceId")
                        .HasColumnType("bigint")
                        .HasColumnName("proc_inst_id");

                    b.Property<int>("State")
                        .HasColumnType("int")
                        .HasColumnName("state");

                    b.Property<long?>("TokenId")
                        .HasColumnType("bigint")
                        .HasColumnName("token_id");

                    b.HasKey("Id");

                    b.HasIndex("ActivityInstanceId");

                    b.HasIndex("ProcessDefinitionId");

                    b.HasIndex("ProcessInstanceId");

                    b.HasIndex("TokenId");

                    b.ToTable("bpm_task", (string)null);
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.Token", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("ActivityId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("activity_id");

                    b.Property<long?>("ActivityInstanceId")
                        .HasColumnType("bigint")
                        .HasColumnName("act_inst_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsMIRoot")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_mi_root");

                    b.Property<bool>("IsScope")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_scope");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_suspended");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<long>("ProcessInstanceId")
                        .HasColumnType("bigint")
                        .HasColumnName("proc_inst_id");

                    b.Property<long?>("SubProcessInstanceId")
                        .HasColumnType("bigint")
                        .HasColumnName("sub_proc_inst_id");

                    b.Property<string>("TransitionId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("transition_id");

                    b.HasKey("Id");

                    b.HasIndex("ActivityInstanceId");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProcessInstanceId");

                    b.HasIndex("SubProcessInstanceId");

                    b.ToTable("bpm_token", (string)null);
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("bpm_user", (string)null);
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.UserGroup", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("user_id");

                    b.Property<string>("GroupId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("group_id");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("bpm_user_group", (string)null);
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.Variable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long?>("ByteArrayId")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_array_id");

                    b.Property<double?>("DoubleValue")
                        .HasColumnType("double")
                        .HasColumnName("double_val");

                    b.Property<long?>("LongValue")
                        .HasColumnType("bigint")
                        .HasColumnName("long_val");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name");

                    b.Property<long?>("ProcessInstanceId")
                        .HasColumnType("bigint")
                        .HasColumnName("proc_inst_id");

                    b.Property<long?>("TaskInstanceId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_id");

                    b.Property<string>("Text")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("text");

                    b.Property<string>("Text2")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("text2");

                    b.Property<long?>("TokenId")
                        .HasColumnType("bigint")
                        .HasColumnName("token_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ByteArrayId");

                    b.HasIndex("ProcessInstanceId");

                    b.HasIndex("TaskInstanceId");

                    b.HasIndex("TokenId");

                    b.ToTable("bpm_proc_data", (string)null);
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.ActivityInstance", b =>
                {
                    b.HasOne("Bpmtk.Engine.Models.ActivityInstance", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bpmtk.Engine.Models.ProcessInstance", "ProcessInstance")
                        .WithMany()
                        .HasForeignKey("ProcessInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bpmtk.Engine.Models.ProcessInstance", "SubProcessInstance")
                        .WithMany()
                        .HasForeignKey("SubProcessInstanceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");

                    b.Navigation("ProcessInstance");

                    b.Navigation("SubProcessInstance");
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.ActivityVariable", b =>
                {
                    b.HasOne("Bpmtk.Engine.Models.ActivityInstance", null)
                        .WithMany("Variables")
                        .HasForeignKey("ActivityInstanceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bpmtk.Engine.Models.ByteArray", "ByteArray")
                        .WithMany()
                        .HasForeignKey("ByteArrayId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ByteArray");
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.Comment", b =>
                {
                    b.HasOne("Bpmtk.Engine.Models.ProcessDefinition", "ProcessDefinition")
                        .WithMany()
                        .HasForeignKey("ProcessDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bpmtk.Engine.Models.ProcessInstance", "ProcessInstance")
                        .WithMany()
                        .HasForeignKey("ProcessInstanceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bpmtk.Engine.Models.TaskInstance", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bpmtk.Engine.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ProcessDefinition");

                    b.Navigation("ProcessInstance");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.Deployment", b =>
                {
                    b.HasOne("Bpmtk.Engine.Models.ByteArray", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bpmtk.Engine.Models.Package", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.EventSubscription", b =>
                {
                    b.HasOne("Bpmtk.Engine.Models.ProcessDefinition", "ProcessDefinition")
                        .WithMany()
                        .HasForeignKey("ProcessDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bpmtk.Engine.Models.ProcessInstance", "ProcessInstance")
                        .WithMany()
                        .HasForeignKey("ProcessInstanceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bpmtk.Engine.Models.Token", "Token")
                        .WithMany()
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ProcessDefinition");

                    b.Navigation("ProcessInstance");

                    b.Navigation("Token");
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.HistoricModel", b =>
                {
                    b.HasOne("Bpmtk.Engine.Models.ByteArray", "Content")
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bpmtk.Engine.Models.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.HistoricPackageItem", b =>
                {
                    b.HasOne("Bpmtk.Engine.Models.ByteArray", "Content")
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bpmtk.Engine.Models.PackageItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.IdentityLink", b =>
                {
                    b.HasOne("Bpmtk.Engine.Models.ActivityInstance", null)
                        .WithMany("IdentityLinks")
                        .HasForeignKey("ActivityInstanceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bpmtk.Engine.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bpmtk.Engine.Models.Package", "Package")
                        .WithMany("IdentityLinks")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bpmtk.Engine.Models.ProcessDefinition", "ProcessDefinition")
                        .WithMany("IdentityLinks")
                        .HasForeignKey("ProcessDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bpmtk.Engine.Models.ProcessInstance", "ProcessInstance")
                        .WithMany("IdentityLinks")
                        .HasForeignKey("ProcessInstanceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bpmtk.Engine.Models.TaskInstance", "Task")
                        .WithMany("IdentityLinks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bpmtk.Engine.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Package");

                    b.Navigation("ProcessDefinition");

                    b.Navigation("ProcessInstance");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.Package", b =>
                {
                    b.HasOne("Bpmtk.Engine.Models.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bpmtk.Engine.Models.ByteArray", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.PackageItem", b =>
                {
                    b.HasOne("Bpmtk.Engine.Models.ByteArray", "Content")
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bpmtk.Engine.Models.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.ProcessDefinition", b =>
                {
                    b.HasOne("Bpmtk.Engine.Models.Deployment", "Deployment")
                        .WithMany("ProcessDefinitions")
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deployment");
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.ProcessInstance", b =>
                {
                    b.HasOne("Bpmtk.Engine.Models.ActivityInstance", "Caller")
                        .WithMany()
                        .HasForeignKey("CallerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bpmtk.Engine.Models.ProcessDefinition", "ProcessDefinition")
                        .WithMany()
                        .HasForeignKey("ProcessDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bpmtk.Engine.Models.Token", "Super")
                        .WithMany()
                        .HasForeignKey("SuperId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bpmtk.Engine.Models.Token", "Token")
                        .WithMany()
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Caller");

                    b.Navigation("ProcessDefinition");

                    b.Navigation("Super");

                    b.Navigation("Token");
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.ScheduledJob", b =>
                {
                    b.HasOne("Bpmtk.Engine.Models.ProcessDefinition", "ProcessDefinition")
                        .WithMany()
                        .HasForeignKey("ProcessDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bpmtk.Engine.Models.ProcessInstance", "ProcessInstance")
                        .WithMany()
                        .HasForeignKey("ProcessInstanceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bpmtk.Engine.Models.TaskInstance", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bpmtk.Engine.Models.Token", "Token")
                        .WithMany()
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ProcessDefinition");

                    b.Navigation("ProcessInstance");

                    b.Navigation("Task");

                    b.Navigation("Token");
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.TaskInstance", b =>
                {
                    b.HasOne("Bpmtk.Engine.Models.ActivityInstance", "ActivityInstance")
                        .WithMany()
                        .HasForeignKey("ActivityInstanceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bpmtk.Engine.Models.ProcessDefinition", "ProcessDefinition")
                        .WithMany()
                        .HasForeignKey("ProcessDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bpmtk.Engine.Models.ProcessInstance", "ProcessInstance")
                        .WithMany()
                        .HasForeignKey("ProcessInstanceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bpmtk.Engine.Models.Token", "Token")
                        .WithMany()
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActivityInstance");

                    b.Navigation("ProcessDefinition");

                    b.Navigation("ProcessInstance");

                    b.Navigation("Token");
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.Token", b =>
                {
                    b.HasOne("Bpmtk.Engine.Models.ActivityInstance", "ActivityInstance")
                        .WithMany()
                        .HasForeignKey("ActivityInstanceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Bpmtk.Engine.Models.Token", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bpmtk.Engine.Models.ProcessInstance", "ProcessInstance")
                        .WithMany()
                        .HasForeignKey("ProcessInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bpmtk.Engine.Models.ProcessInstance", "SubProcessInstance")
                        .WithMany()
                        .HasForeignKey("SubProcessInstanceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActivityInstance");

                    b.Navigation("Parent");

                    b.Navigation("ProcessInstance");

                    b.Navigation("SubProcessInstance");
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.UserGroup", b =>
                {
                    b.HasOne("Bpmtk.Engine.Models.Group", "Group")
                        .WithMany("Users")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bpmtk.Engine.Models.User", "User")
                        .WithMany("Groups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.Variable", b =>
                {
                    b.HasOne("Bpmtk.Engine.Models.ByteArray", "ByteArray")
                        .WithMany()
                        .HasForeignKey("ByteArrayId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bpmtk.Engine.Models.ProcessInstance", "ProcessInstance")
                        .WithMany("Variables")
                        .HasForeignKey("ProcessInstanceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bpmtk.Engine.Models.TaskInstance", null)
                        .WithMany("Variables")
                        .HasForeignKey("TaskInstanceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bpmtk.Engine.Models.Token", null)
                        .WithMany("Variables")
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ByteArray");

                    b.Navigation("ProcessInstance");
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.ActivityInstance", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("IdentityLinks");

                    b.Navigation("Variables");
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.Deployment", b =>
                {
                    b.Navigation("ProcessDefinitions");
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.Group", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.Package", b =>
                {
                    b.Navigation("IdentityLinks");
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.ProcessDefinition", b =>
                {
                    b.Navigation("IdentityLinks");
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.ProcessInstance", b =>
                {
                    b.Navigation("IdentityLinks");

                    b.Navigation("Variables");
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.TaskInstance", b =>
                {
                    b.Navigation("IdentityLinks");

                    b.Navigation("Variables");
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.Token", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Variables");
                });

            modelBuilder.Entity("Bpmtk.Engine.Models.User", b =>
                {
                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
